language: go
go:
  - 1.11.x
  - 1.12.x
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build -mod vendor ./cmd/...
  - env GO111MODULE=on go test -mod vendor -v ./...