version: "3.1"

services:
  ssh_test:
    build:
      context: .
      args:
        - SSH_HOSTNAME=${SSH_HOSTNAME}
    volumes:
      - "~/.cloudflared/:/root/.cloudflared"
    env_file:
     - .env
    environment:
      - AUTHORIZED_KEYS_SSH_CONFIG=/root/.ssh/authorized_keys_config
      - SHORT_LIVED_CERT_SSH_CONFIG=/root/.ssh/short_lived_cert_config
      - REMOTE_SCP_FILENAME=scp_test.txt
      - ROOT_ONLY_TEST_FILE_PATH=~/permission_test.txt
    entrypoint: "python tests.py"
