on: [push, pull_request]
name: Check
jobs:
  check:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install go-sumtype
      run: go get github.com/sudarshan-reddy/go-sumtype
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
