name: Release

on:
  workflow_dispatch: # 手动发布
  workflow_run: # 当 build 流程成功完成后自动触发
    workflows: ["Build Artifacts"]
    types: [completed]
    
jobs:
  release:
    runs-on: ubuntu-latest

    # 仅在Build工作流成功时运行
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')