name: Release

on:
  workflow_run:
    workflows: ["Build"]  # 监听名为“Build”的工作流
    types:
      - completed  # 当Build工作流完成时触发
    branches:
      - master  # 限定分支
jobs:
  release:
    runs-on: ubuntu-latest

    # 仅在Build工作流成功时运行
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')